name: Publish Wiki
on:
  push:
    branches: [master]
    paths:
      - Wiki/**
      - .github/workflows/Publish Wiki.yml
  workflow_dispatch:
concurrency:
  group: Publish Wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@main  # Replace 'main' with 'v4' when problems arise with updates.
      - name: Placeholder processing the wiki
        uses: richardrigutins/replace-in-files@main  # Replace 'main' with 'v2' when problems arise with updates.
        with:
          files: Wiki/*.md
          search-text: '{{ GITHUB_REPO }}'
          replacement-text: '${{ github.server_url }}/${{ github.repository }}'
#     - name: Spellchecking the Wiki
#       uses: rojopolis/spellcheck-github-actions@master  # Replace 'master' with 'v0' when problems arise with updates.
#       with:
#         source_files: Wiki/*.md
#         task_name: Markdown
#         ignores:
#           - code
#           - pre
      - name: Publishing processed Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@master  # Replace 'master' with 'v4' when problems arise with updates.
        with:
          path: Wiki/
